package com.zhku.meeting.entities;

import java.util.Date;

public class ApplicationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.application_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.apply_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.audit_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.audit_status
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.reject_reason
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.apply_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.apply_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer applySlot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private String meetingTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer meetingSize;

    private String roomNo;
    private String deptName;

    public String getRoomNo() {
        return roomNo;
    }

    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.application_id
     *
     * @return the value of application_record.application_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.application_id
     *
     * @param applicationId the value for application_record.application_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.dept_id
     *
     * @return the value of application_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.dept_id
     *
     * @param deptId the value for application_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.room_id
     *
     * @return the value of application_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.room_id
     *
     * @param roomId the value for application_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.apply_time
     *
     * @return the value of application_record.apply_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.apply_time
     *
     * @param applyTime the value for application_record.apply_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.audit_time
     *
     * @return the value of application_record.audit_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.audit_time
     *
     * @param auditTime the value for application_record.audit_time
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.audit_status
     *
     * @return the value of application_record.audit_status
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.audit_status
     *
     * @param auditStatus the value for application_record.audit_status
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.reject_reason
     *
     * @return the value of application_record.reject_reason
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.reject_reason
     *
     * @param rejectReason the value for application_record.reject_reason
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason == null ? null : rejectReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.apply_date
     *
     * @return the value of application_record.apply_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.apply_date
     *
     * @param applyDate the value for application_record.apply_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.apply_slot
     *
     * @return the value of application_record.apply_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getApplySlot() {
        return applySlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.apply_slot
     *
     * @param applySlot the value for application_record.apply_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setApplySlot(Integer applySlot) {
        this.applySlot = applySlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.meeting_theme
     *
     * @return the value of application_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public String getMeetingTheme() {
        return meetingTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.meeting_theme
     *
     * @param meetingTheme the value for application_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingTheme(String meetingTheme) {
        this.meetingTheme = meetingTheme == null ? null : meetingTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_record.meeting_size
     *
     * @return the value of application_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getMeetingSize() {
        return meetingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_record.meeting_size
     *
     * @param meetingSize the value for application_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingSize(Integer meetingSize) {
        this.meetingSize = meetingSize;
    }

    public ApplicationRecord() {
    }

    public ApplicationRecord(Integer deptId, Integer roomId, Date applyTime, Date applyDate, Integer applySlot, String meetingTheme, Integer meetingSize) {
        this.deptId = deptId;
        this.roomId = roomId;
        this.applyTime = applyTime;
        this.applyDate = applyDate;
        this.applySlot = applySlot;
        this.meetingTheme = meetingTheme;
        this.meetingSize = meetingSize;
    }
}