package com.zhku.meeting.entities;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_id
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_phone
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    private String deptPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_no
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    private String deptNo;


    private String deptPassword;


    public String getDeptPassword() {
        return deptPassword;
    }

    public void setDeptPassword(String deptPassword) {
        this.deptPassword = deptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_id
     *
     * @return the value of department.dept_id
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_id
     *
     * @param deptId the value for department.dept_id
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_name
     *
     * @param deptName the value for department.dept_name
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_phone
     *
     * @return the value of department.dept_phone
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public String getDeptPhone() {
        return deptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_phone
     *
     * @param deptPhone the value for department.dept_phone
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_no
     *
     * @return the value of department.dept_no
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_no
     *
     * @param deptNo the value for department.dept_no
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    public Department() {
    }

    public Department(String deptName, String deptPhone, String deptNo ,String deptPassword) {
        this.deptName = deptName;
        this.deptPhone = deptPhone;
        this.deptNo = deptNo;
        this.deptPassword = deptPassword;
    }
}