package com.zhku.meeting.entities;

import java.util.Date;

public class MeetingRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.record_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private String meetingTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer meetingSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.meeting_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Date meetingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_record.meeting_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    private Integer meetingSlot;

    private Integer applyId;

    public Integer getApplyId() {
        return applyId;
    }

    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    private String deptName;
    private String roomNo;

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getRoomNo() {
        return roomNo;
    }

    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.record_id
     *
     * @return the value of meeting_record.record_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.record_id
     *
     * @param recordId the value for meeting_record.record_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.meeting_theme
     *
     * @return the value of meeting_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public String getMeetingTheme() {
        return meetingTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.meeting_theme
     *
     * @param meetingTheme the value for meeting_record.meeting_theme
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingTheme(String meetingTheme) {
        this.meetingTheme = meetingTheme == null ? null : meetingTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.meeting_size
     *
     * @return the value of meeting_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getMeetingSize() {
        return meetingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.meeting_size
     *
     * @param meetingSize the value for meeting_record.meeting_size
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingSize(Integer meetingSize) {
        this.meetingSize = meetingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.dept_id
     *
     * @return the value of meeting_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.dept_id
     *
     * @param deptId the value for meeting_record.dept_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.room_id
     *
     * @return the value of meeting_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.room_id
     *
     * @param roomId the value for meeting_record.room_id
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.meeting_date
     *
     * @return the value of meeting_record.meeting_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Date getMeetingDate() {
        return meetingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.meeting_date
     *
     * @param meetingDate the value for meeting_record.meeting_date
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_record.meeting_slot
     *
     * @return the value of meeting_record.meeting_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public Integer getMeetingSlot() {
        return meetingSlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_record.meeting_slot
     *
     * @param meetingSlot the value for meeting_record.meeting_slot
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    public void setMeetingSlot(Integer meetingSlot) {
        this.meetingSlot = meetingSlot;
    }

    public MeetingRecord() {
    }

    public MeetingRecord(String meetingTheme, Integer meetingSize, Integer deptId, Integer roomId, Date meetingDate, Integer meetingSlot) {
        this.meetingTheme = meetingTheme;
        this.meetingSize = meetingSize;
        this.deptId = deptId;
        this.roomId = roomId;
        this.meetingDate = meetingDate;
        this.meetingSlot = meetingSlot;
    }
}