package com.zhku.meeting.entities;

public class ShowStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.id
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.room_id
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.room_no
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private String roomNo;


    private int roomSize;

    public ShowStatus(Integer id, Integer size) {
        this.roomId =id;
        this.roomSize=size;
    }

    public ShowStatus() {
    }

    public int getRoomSize() {
        return roomSize;
    }

    public void setRoomSize(int roomSize) {
        this.roomSize = roomSize;
    }


    private boolean air;
    private boolean projector;

    public boolean isAir() {
        return air;
    }

    public void setAir(boolean air) {
        this.air = air;
    }

    public boolean isProjector() {
        return projector;
    }

    public void setProjector(boolean projector) {
        this.projector = projector;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.one
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Boolean one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.two
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Boolean two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.three
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Boolean three;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.four
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Boolean four;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.five
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    private Boolean five;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.room_id
     *
     * @return the value of status.room_id
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.room_id
     *
     * @param roomId the value for status.room_id
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.room_no
     *
     * @return the value of status.room_no
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public String getRoomNo() {
        return roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.room_no
     *
     * @param roomNo the value for status.room_no
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo == null ? null : roomNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.one
     *
     * @return the value of status.one
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Boolean getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.one
     *
     * @param one the value for status.one
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setOne(Boolean one) {
        this.one = one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.two
     *
     * @return the value of status.two
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Boolean getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.two
     *
     * @param two the value for status.two
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setTwo(Boolean two) {
        this.two = two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.three
     *
     * @return the value of status.three
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Boolean getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.three
     *
     * @param three the value for status.three
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setThree(Boolean three) {
        this.three = three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.four
     *
     * @return the value of status.four
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Boolean getFour() {
        return four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.four
     *
     * @param four the value for status.four
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setFour(Boolean four) {
        this.four = four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.five
     *
     * @return the value of status.five
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public Boolean getFive() {
        return five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.five
     *
     * @param five the value for status.five
     *
     * @mbg.generated Mon Jun 15 21:19:27 CST 2020
     */
    public void setFive(Boolean five) {
        this.five = five;
    }
}