package com.zhku.meeting.mapper;

import com.zhku.meeting.entities.MeetingRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeetingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_record
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_record
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    int insert(MeetingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_record
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    MeetingRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_record
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    List<MeetingRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_record
     *
     * @mbg.generated Sat Jun 13 18:04:24 CST 2020
     */
    int updateByPrimaryKey(MeetingRecord record);


    List<MeetingRecord> selectByCondition(MeetingRecord record,Integer pass);

    int deleteByCondition(@Param("roomId") Integer id);

    int deleteByDeptId(@Param("deptId") Integer id);
}